// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.mariadb.core.global;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.mariadb.core.MyGlobal.*;
          /* Used for table bits in join */

/* often used type names - opaque declarations */
@Opaque @Properties(inherit = org.swdc.mariadb.conf.MyGlobalConfigure.class)
public class CHARSET_INFO extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public CHARSET_INFO() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CHARSET_INFO(Pointer p) { super(p); }
}
