// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.mariadb.core.global;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.mariadb.core.MyGlobal.*;

@Opaque @Properties(inherit = org.swdc.mariadb.conf.MyGlobalConfigure.class)
public class LEX_STRING extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public LEX_STRING() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LEX_STRING(Pointer p) { super(p); }
}
