// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.mariadb.core.global;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.mariadb.core.MyGlobal.*;


@Properties(inherit = org.swdc.mariadb.conf.MyGlobalConfigure.class)
public class list_walk_action extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    list_walk_action(Pointer p) { super(p); }
    protected list_walk_action() { allocate(); }
    private native void allocate();
    public native int call(Pointer arg0,Pointer arg1);
}
