// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core.io;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class ClangIO extends org.swdc.libclang.conf.LibClangIOConfigure {
    static { Loader.load(); }

// Parsed from CXFile.h



// #ifndef LLVM_CLANG_C_CXFILE_H
// #define LLVM_CLANG_C_CXFILE_H

// #include <time.h>

// #include "CXString.h"
// #include "ExternC.h"
// #include "Platform.h"
// Targeting CXFile.java



/**
 * Retrieve the complete file and path name of the given file.
 */
public static native @ByVal CXString clang_getFileName(CXFile SFile);

/**
 * Retrieve the last modification time of the given file.
 */
public static native @ByVal @Cast("time_t*") Pointer clang_getFileTime(CXFile SFile);
// Targeting CXFileUniqueID.java



/**
 * Retrieve the unique ID for the given \c file.
 *
 * @param file the file to get the ID for.
 * @param outID stores the returned CXFileUniqueID.
 * @return If there was a failure getting the unique ID, returns non-zero,
 * otherwise returns 0.
 */
public static native int clang_getFileUniqueID(CXFile file, CXFileUniqueID outID);

/**
 * Returns non-zero if the \c file1 and \c file2 point to the same file,
 * or they are both NULL.
 */
public static native int clang_File_isEqual(CXFile file1, CXFile file2);

/**
 * Returns the real path name of \c file.
 *
 * An empty string may be returned. Use \c clang_getFileName() in that case.
 */
public static native @ByVal CXString clang_File_tryGetRealPathName(CXFile file);

/**
 * \}
 */

// #endif


// Parsed from CXErrorCode.h



// #ifndef LLVM_CLANG_C_CXERRORCODE_H
// #define LLVM_CLANG_C_CXERRORCODE_H

// #include "ExternC.h"
// #include "Platform.h"

/**
 * Error codes returned by libclang routines.
 *
 * Zero (\c CXError_Success) is the only error code indicating success.  Other
 * error codes, including not yet assigned non-zero values, indicate errors.
 */
/** enum CXErrorCode */
public static final int
  /**
   * No error.
   */
  CXError_Success = 0,

  /**
   * A generic error code, no further details are available.
   *
   * Errors of this kind can get their own specific error codes in future
   * libclang versions.
   */
  CXError_Failure = 1,

  /**
   * libclang crashed while performing the requested operation.
   */
  CXError_Crashed = 2,

  /**
   * The function detected that the arguments violate the function
   * contract.
   */
  CXError_InvalidArguments = 3,

  /**
   * An AST deserialization error has occurred.
   */
  CXError_ASTReadError = 4;

// #endif



// Parsed from CXString.h



// #ifndef LLVM_CLANG_C_CXSTRING_H
// #define LLVM_CLANG_C_CXSTRING_H

// #include "ExternC.h"
// #include "Platform.h"
// Targeting CXString.java


// Targeting CXStringSet.java



/**
 * Retrieve the character data associated with the given string.
 */
public static native @Cast("const char*") BytePointer clang_getCString(@ByVal CXString string);

/**
 * Free the given string.
 */
public static native void clang_disposeString(@ByVal CXString string);

/**
 * Free the given string set.
 */
public static native void clang_disposeStringSet(CXStringSet set);

/**
 * \}
 */

// #endif



// Parsed from CXDiagnostic.h



// #ifndef LLVM_CLANG_C_CXDIAGNOSTIC_H
// #define LLVM_CLANG_C_CXDIAGNOSTIC_H

// #include "CXSourceLocation.h"
// #include "CXString.h"
// #include "ExternC.h"
// #include "Platform.h"

/**
 * \defgroup CINDEX_DIAG Diagnostic reporting
 *
 * \{
 */

/**
 * Describes the severity of a particular diagnostic.
 */
/** enum CXDiagnosticSeverity */
public static final int
  /**
   * A diagnostic that has been suppressed, e.g., by a command-line
   * option.
   */
  CXDiagnostic_Ignored = 0,

  /**
   * This diagnostic is a note that should be attached to the
   * previous (non-note) diagnostic.
   */
  CXDiagnostic_Note = 1,

  /**
   * This diagnostic indicates suspicious code that may not be
   * wrong.
   */
  CXDiagnostic_Warning = 2,

  /**
   * This diagnostic indicates that the code is ill-formed.
   */
  CXDiagnostic_Error = 3,

  /**
   * This diagnostic indicates that the code is ill-formed such
   * that future parser recovery is unlikely to produce useful
   * results.
   */
  CXDiagnostic_Fatal = 4;
// Targeting CXDiagnostic.java


// Targeting CXDiagnosticSet.java



/**
 * Determine the number of diagnostics in a CXDiagnosticSet.
 */
public static native @Cast("unsigned") int clang_getNumDiagnosticsInSet(CXDiagnosticSet Diags);

/**
 * Retrieve a diagnostic associated with the given CXDiagnosticSet.
 *
 * @param Diags the CXDiagnosticSet to query.
 * @param Index the zero-based diagnostic number to retrieve.
 *
 * @return the requested diagnostic. This diagnostic must be freed
 * via a call to \c clang_disposeDiagnostic().
 */
public static native CXDiagnostic clang_getDiagnosticInSet(CXDiagnosticSet Diags,
                                                     @Cast("unsigned") int Index);

/**
 * Describes the kind of error that occurred (if any) in a call to
 * \c clang_loadDiagnostics.
 */
/** enum CXLoadDiag_Error */
public static final int
  /**
   * Indicates that no error occurred.
   */
  CXLoadDiag_None = 0,

  /**
   * Indicates that an unknown error occurred while attempting to
   * deserialize diagnostics.
   */
  CXLoadDiag_Unknown = 1,

  /**
   * Indicates that the file containing the serialized diagnostics
   * could not be opened.
   */
  CXLoadDiag_CannotLoad = 2,

  /**
   * Indicates that the serialized diagnostics file is invalid or
   * corrupt.
   */
  CXLoadDiag_InvalidFile = 3;

/**
 * Deserialize a set of diagnostics from a Clang diagnostics bitcode
 * file.
 *
 * @param file The name of the file to deserialize.
 * @param error A pointer to a enum value recording if there was a problem
 *        deserializing the diagnostics.
 * @param errorString A pointer to a CXString for recording the error string
 *        if the file was not successfully loaded.
 *
 * @return A loaded CXDiagnosticSet if successful, and NULL otherwise.  These
 * diagnostics should be released using clang_disposeDiagnosticSet().
 */
public static native CXDiagnosticSet clang_loadDiagnostics(
    @Cast("const char*") BytePointer file, @Cast("CXLoadDiag_Error*") IntPointer error, CXString errorString);
public static native CXDiagnosticSet clang_loadDiagnostics(
    String file, @Cast("CXLoadDiag_Error*") IntBuffer error, CXString errorString);
public static native CXDiagnosticSet clang_loadDiagnostics(
    @Cast("const char*") BytePointer file, @Cast("CXLoadDiag_Error*") int[] error, CXString errorString);
public static native CXDiagnosticSet clang_loadDiagnostics(
    String file, @Cast("CXLoadDiag_Error*") IntPointer error, CXString errorString);
public static native CXDiagnosticSet clang_loadDiagnostics(
    @Cast("const char*") BytePointer file, @Cast("CXLoadDiag_Error*") IntBuffer error, CXString errorString);
public static native CXDiagnosticSet clang_loadDiagnostics(
    String file, @Cast("CXLoadDiag_Error*") int[] error, CXString errorString);

/**
 * Release a CXDiagnosticSet and all of its contained diagnostics.
 */
public static native void clang_disposeDiagnosticSet(CXDiagnosticSet Diags);

/**
 * Retrieve the child diagnostics of a CXDiagnostic.
 *
 * This CXDiagnosticSet does not need to be released by
 * clang_disposeDiagnosticSet.
 */
public static native CXDiagnosticSet clang_getChildDiagnostics(CXDiagnostic D);

/**
 * Destroy a diagnostic.
 */
public static native void clang_disposeDiagnostic(CXDiagnostic Diagnostic);

/**
 * Options to control the display of diagnostics.
 *
 * The values in this enum are meant to be combined to customize the
 * behavior of \c clang_formatDiagnostic().
 */
/** enum CXDiagnosticDisplayOptions */
public static final int
  /**
   * Display the source-location information where the
   * diagnostic was located.
   *
   * When set, diagnostics will be prefixed by the file, line, and
   * (optionally) column to which the diagnostic refers. For example,
   *
   * <pre>{@code
   * test.c:28: warning: extra tokens at end of #endif directive
   * }</pre>
   *
   * This option corresponds to the clang flag \c -fshow-source-location.
   */
  CXDiagnostic_DisplaySourceLocation = 0x01,

  /**
   * If displaying the source-location information of the
   * diagnostic, also include the column number.
   *
   * This option corresponds to the clang flag \c -fshow-column.
   */
  CXDiagnostic_DisplayColumn = 0x02,

  /**
   * If displaying the source-location information of the
   * diagnostic, also include information about source ranges in a
   * machine-parsable format.
   *
   * This option corresponds to the clang flag
   * \c -fdiagnostics-print-source-range-info.
   */
  CXDiagnostic_DisplaySourceRanges = 0x04,

  /**
   * Display the option name associated with this diagnostic, if any.
   *
   * The option name displayed (e.g., -Wconversion) will be placed in brackets
   * after the diagnostic text. This option corresponds to the clang flag
   * \c -fdiagnostics-show-option.
   */
  CXDiagnostic_DisplayOption = 0x08,

  /**
   * Display the category number associated with this diagnostic, if any.
   *
   * The category number is displayed within brackets after the diagnostic text.
   * This option corresponds to the clang flag
   * \c -fdiagnostics-show-category=id.
   */
  CXDiagnostic_DisplayCategoryId = 0x10,

  /**
   * Display the category name associated with this diagnostic, if any.
   *
   * The category name is displayed within brackets after the diagnostic text.
   * This option corresponds to the clang flag
   * \c -fdiagnostics-show-category=name.
   */
  CXDiagnostic_DisplayCategoryName = 0x20;

/**
 * Format the given diagnostic in a manner that is suitable for display.
 *
 * This routine will format the given diagnostic to a string, rendering
 * the diagnostic according to the various options given. The
 * \c clang_defaultDiagnosticDisplayOptions() function returns the set of
 * options that most closely mimics the behavior of the clang compiler.
 *
 * @param Diagnostic The diagnostic to print.
 *
 * @param Options A set of options that control the diagnostic display,
 * created by combining \c CXDiagnosticDisplayOptions values.
 *
 * @return A new string containing for formatted diagnostic.
 */
public static native @ByVal CXString clang_formatDiagnostic(CXDiagnostic Diagnostic,
                                               @Cast("unsigned") int Options);

/**
 * Retrieve the set of display options most similar to the
 * default behavior of the clang compiler.
 *
 * @return A set of display options suitable for use with \c
 * clang_formatDiagnostic().
 */
public static native @Cast("unsigned") int clang_defaultDiagnosticDisplayOptions();

/**
 * Determine the severity of the given diagnostic.
 */
public static native @Cast("CXDiagnosticSeverity") int clang_getDiagnosticSeverity(CXDiagnostic arg0);

/**
 * Retrieve the source location of the given diagnostic.
 *
 * This location is where Clang would print the caret ('^') when
 * displaying the diagnostic on the command line.
 */
public static native @ByVal CXSourceLocation clang_getDiagnosticLocation(CXDiagnostic arg0);

/**
 * Retrieve the text of the given diagnostic.
 */
public static native @ByVal CXString clang_getDiagnosticSpelling(CXDiagnostic arg0);

/**
 * Retrieve the name of the command-line option that enabled this
 * diagnostic.
 *
 * @param Diag The diagnostic to be queried.
 *
 * @param Disable If non-NULL, will be set to the option that disables this
 * diagnostic (if any).
 *
 * @return A string that contains the command-line option used to enable this
 * warning, such as "-Wconversion" or "-pedantic".
 */
public static native @ByVal CXString clang_getDiagnosticOption(CXDiagnostic Diag,
                                                  CXString Disable);

/**
 * Retrieve the category number for this diagnostic.
 *
 * Diagnostics can be categorized into groups along with other, related
 * diagnostics (e.g., diagnostics under the same warning flag). This routine
 * retrieves the category number for the given diagnostic.
 *
 * @return The number of the category that contains this diagnostic, or zero
 * if this diagnostic is uncategorized.
 */
public static native @Cast("unsigned") int clang_getDiagnosticCategory(CXDiagnostic arg0);

/**
 * Retrieve the name of a particular diagnostic category.  This
 *  is now deprecated.  Use clang_getDiagnosticCategoryText()
 *  instead.
 *
 * @param Category A diagnostic category number, as returned by
 * \c clang_getDiagnosticCategory().
 *
 * @return The name of the given diagnostic category.
 */

/**
 * Retrieve the diagnostic category text for a given diagnostic.
 *
 * @return The text of the given diagnostic category.
 */
public static native @ByVal CXString clang_getDiagnosticCategoryText(CXDiagnostic arg0);

/**
 * Determine the number of source ranges associated with the given
 * diagnostic.
 */
public static native @Cast("unsigned") int clang_getDiagnosticNumRanges(CXDiagnostic arg0);

/**
 * Retrieve a source range associated with the diagnostic.
 *
 * A diagnostic's source ranges highlight important elements in the source
 * code. On the command line, Clang displays source ranges by
 * underlining them with '~' characters.
 *
 * @param Diagnostic the diagnostic whose range is being extracted.
 *
 * @param Range the zero-based index specifying which range to
 *
 * @return the requested source range.
 */
public static native @ByVal CXSourceRange clang_getDiagnosticRange(CXDiagnostic Diagnostic,
                                                      @Cast("unsigned") int Range);

/**
 * Determine the number of fix-it hints associated with the
 * given diagnostic.
 */
public static native @Cast("unsigned") int clang_getDiagnosticNumFixIts(CXDiagnostic Diagnostic);

/**
 * Retrieve the replacement information for a given fix-it.
 *
 * Fix-its are described in terms of a source range whose contents
 * should be replaced by a string. This approach generalizes over
 * three kinds of operations: removal of source code (the range covers
 * the code to be removed and the replacement string is empty),
 * replacement of source code (the range covers the code to be
 * replaced and the replacement string provides the new code), and
 * insertion (both the start and end of the range point at the
 * insertion location, and the replacement string provides the text to
 * insert).
 *
 * @param Diagnostic The diagnostic whose fix-its are being queried.
 *
 * @param FixIt The zero-based index of the fix-it.
 *
 * @param ReplacementRange The source range whose contents will be
 * replaced with the returned replacement string. Note that source
 * ranges are half-open ranges [a, b), so the source code should be
 * replaced from a and up to (but not including) b.
 *
 * @return A string containing text that should be replace the source
 * code indicated by the \c ReplacementRange.
 */
public static native @ByVal CXString clang_getDiagnosticFixIt(
    CXDiagnostic Diagnostic, @Cast("unsigned") int FixIt, CXSourceRange ReplacementRange);

/**
 * \}
 */

// #endif


// Parsed from CXSourceLocation.h


// #ifndef LLVM_CLANG_C_CXSOURCE_LOCATION_H
// #define LLVM_CLANG_C_CXSOURCE_LOCATION_H

// #include "CXFile.h"
// #include "CXString.h"
// #include "ExternC.h"
// #include "Platform.h"
// Targeting CXSourceLocation.java


// Targeting CXSourceRange.java



/**
 * Retrieve a NULL (invalid) source location.
 */
public static native @ByVal CXSourceLocation clang_getNullLocation();

/**
 * Determine whether two source locations, which must refer into
 * the same translation unit, refer to exactly the same point in the source
 * code.
 *
 * @return non-zero if the source locations refer to the same location, zero
 * if they refer to different locations.
 */
public static native @Cast("unsigned") int clang_equalLocations(@ByVal CXSourceLocation loc1,
                                             @ByVal CXSourceLocation loc2);

/**
 * Returns non-zero if the given source location is in a system header.
 */
public static native int clang_Location_isInSystemHeader(@ByVal CXSourceLocation location);

/**
 * Returns non-zero if the given source location is in the main file of
 * the corresponding translation unit.
 */
public static native int clang_Location_isFromMainFile(@ByVal CXSourceLocation location);

/**
 * Retrieve a NULL (invalid) source range.
 */
public static native @ByVal CXSourceRange clang_getNullRange();

/**
 * Retrieve a source range given the beginning and ending source
 * locations.
 */
public static native @ByVal CXSourceRange clang_getRange(@ByVal CXSourceLocation begin,
                                            @ByVal CXSourceLocation end);

/**
 * Determine whether two ranges are equivalent.
 *
 * @return non-zero if the ranges are the same, zero if they differ.
 */
public static native @Cast("unsigned") int clang_equalRanges(@ByVal CXSourceRange range1,
                                          @ByVal CXSourceRange range2);

/**
 * Returns non-zero if \p range is null.
 */
public static native int clang_Range_isNull(@ByVal CXSourceRange range);

/**
 * Retrieve the file, line, column, and offset represented by
 * the given source location.
 *
 * If the location refers into a macro expansion, retrieves the
 * location of the macro expansion.
 *
 * @param location the location within a source file that will be decomposed
 * into its parts.
 *
 * @param file [out] if non-NULL, will be set to the file to which the given
 * source location points.
 *
 * @param line [out] if non-NULL, will be set to the line to which the given
 * source location points.
 *
 * @param column [out] if non-NULL, will be set to the column to which the given
 * source location points.
 *
 * @param offset [out] if non-NULL, will be set to the offset into the
 * buffer to which the given source location points.
 */
public static native void clang_getExpansionLocation(@ByVal CXSourceLocation location,
                                               @ByPtrPtr CXFile file, @Cast("unsigned*") IntPointer line,
                                               @Cast("unsigned*") IntPointer column,
                                               @Cast("unsigned*") IntPointer offset);
public static native void clang_getExpansionLocation(@ByVal CXSourceLocation location,
                                               @ByPtrPtr CXFile file, @Cast("unsigned*") IntBuffer line,
                                               @Cast("unsigned*") IntBuffer column,
                                               @Cast("unsigned*") IntBuffer offset);
public static native void clang_getExpansionLocation(@ByVal CXSourceLocation location,
                                               @ByPtrPtr CXFile file, @Cast("unsigned*") int[] line,
                                               @Cast("unsigned*") int[] column,
                                               @Cast("unsigned*") int[] offset);

/**
 * Retrieve the file, line and column represented by the given source
 * location, as specified in a # line directive.
 *
 * Example: given the following source code in a file somefile.c
 *
 * <pre>{@code
 * #123 "dummy.c" 1
 *
 * static int func(void)
 * {
 *     return 0;
 * }
 * }</pre>
 *
 * the location information returned by this function would be
 *
 * File: dummy.c Line: 124 Column: 12
 *
 * whereas clang_getExpansionLocation would have returned
 *
 * File: somefile.c Line: 3 Column: 12
 *
 * @param location the location within a source file that will be decomposed
 * into its parts.
 *
 * @param filename [out] if non-NULL, will be set to the filename of the
 * source location. Note that filenames returned will be for "virtual" files,
 * which don't necessarily exist on the machine running clang - e.g. when
 * parsing preprocessed output obtained from a different environment. If
 * a non-NULL value is passed in, remember to dispose of the returned value
 * using \c clang_disposeString() once you've finished with it. For an invalid
 * source location, an empty string is returned.
 *
 * @param line [out] if non-NULL, will be set to the line number of the
 * source location. For an invalid source location, zero is returned.
 *
 * @param column [out] if non-NULL, will be set to the column number of the
 * source location. For an invalid source location, zero is returned.
 */
public static native void clang_getPresumedLocation(@ByVal CXSourceLocation location,
                                              CXString filename,
                                              @Cast("unsigned*") IntPointer line, @Cast("unsigned*") IntPointer column);
public static native void clang_getPresumedLocation(@ByVal CXSourceLocation location,
                                              CXString filename,
                                              @Cast("unsigned*") IntBuffer line, @Cast("unsigned*") IntBuffer column);
public static native void clang_getPresumedLocation(@ByVal CXSourceLocation location,
                                              CXString filename,
                                              @Cast("unsigned*") int[] line, @Cast("unsigned*") int[] column);

/**
 * Legacy API to retrieve the file, line, column, and offset represented
 * by the given source location.
 *
 * This interface has been replaced by the newer interface
 * #clang_getExpansionLocation(). See that interface's documentation for
 * details.
 */
public static native void clang_getInstantiationLocation(@ByVal CXSourceLocation location,
                                                   @ByPtrPtr CXFile file, @Cast("unsigned*") IntPointer line,
                                                   @Cast("unsigned*") IntPointer column,
                                                   @Cast("unsigned*") IntPointer offset);
public static native void clang_getInstantiationLocation(@ByVal CXSourceLocation location,
                                                   @ByPtrPtr CXFile file, @Cast("unsigned*") IntBuffer line,
                                                   @Cast("unsigned*") IntBuffer column,
                                                   @Cast("unsigned*") IntBuffer offset);
public static native void clang_getInstantiationLocation(@ByVal CXSourceLocation location,
                                                   @ByPtrPtr CXFile file, @Cast("unsigned*") int[] line,
                                                   @Cast("unsigned*") int[] column,
                                                   @Cast("unsigned*") int[] offset);

/**
 * Retrieve the file, line, column, and offset represented by
 * the given source location.
 *
 * If the location refers into a macro instantiation, return where the
 * location was originally spelled in the source file.
 *
 * @param location the location within a source file that will be decomposed
 * into its parts.
 *
 * @param file [out] if non-NULL, will be set to the file to which the given
 * source location points.
 *
 * @param line [out] if non-NULL, will be set to the line to which the given
 * source location points.
 *
 * @param column [out] if non-NULL, will be set to the column to which the given
 * source location points.
 *
 * @param offset [out] if non-NULL, will be set to the offset into the
 * buffer to which the given source location points.
 */
public static native void clang_getSpellingLocation(@ByVal CXSourceLocation location,
                                              @ByPtrPtr CXFile file, @Cast("unsigned*") IntPointer line,
                                              @Cast("unsigned*") IntPointer column,
                                              @Cast("unsigned*") IntPointer offset);
public static native void clang_getSpellingLocation(@ByVal CXSourceLocation location,
                                              @ByPtrPtr CXFile file, @Cast("unsigned*") IntBuffer line,
                                              @Cast("unsigned*") IntBuffer column,
                                              @Cast("unsigned*") IntBuffer offset);
public static native void clang_getSpellingLocation(@ByVal CXSourceLocation location,
                                              @ByPtrPtr CXFile file, @Cast("unsigned*") int[] line,
                                              @Cast("unsigned*") int[] column,
                                              @Cast("unsigned*") int[] offset);

/**
 * Retrieve the file, line, column, and offset represented by
 * the given source location.
 *
 * If the location refers into a macro expansion, return where the macro was
 * expanded or where the macro argument was written, if the location points at
 * a macro argument.
 *
 * @param location the location within a source file that will be decomposed
 * into its parts.
 *
 * @param file [out] if non-NULL, will be set to the file to which the given
 * source location points.
 *
 * @param line [out] if non-NULL, will be set to the line to which the given
 * source location points.
 *
 * @param column [out] if non-NULL, will be set to the column to which the given
 * source location points.
 *
 * @param offset [out] if non-NULL, will be set to the offset into the
 * buffer to which the given source location points.
 */
public static native void clang_getFileLocation(@ByVal CXSourceLocation location,
                                          @ByPtrPtr CXFile file, @Cast("unsigned*") IntPointer line,
                                          @Cast("unsigned*") IntPointer column, @Cast("unsigned*") IntPointer offset);
public static native void clang_getFileLocation(@ByVal CXSourceLocation location,
                                          @ByPtrPtr CXFile file, @Cast("unsigned*") IntBuffer line,
                                          @Cast("unsigned*") IntBuffer column, @Cast("unsigned*") IntBuffer offset);
public static native void clang_getFileLocation(@ByVal CXSourceLocation location,
                                          @ByPtrPtr CXFile file, @Cast("unsigned*") int[] line,
                                          @Cast("unsigned*") int[] column, @Cast("unsigned*") int[] offset);

/**
 * Retrieve a source location representing the first character within a
 * source range.
 */
public static native @ByVal CXSourceLocation clang_getRangeStart(@ByVal CXSourceRange range);

/**
 * Retrieve a source location representing the last character within a
 * source range.
 */
public static native @ByVal CXSourceLocation clang_getRangeEnd(@ByVal CXSourceRange range);
// Targeting CXSourceRangeList.java



/**
 * Destroy the given \c CXSourceRangeList.
 */
public static native void clang_disposeSourceRangeList(CXSourceRangeList ranges);

/**
 * \}
 */

// #endif


}
