// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core.io;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.libclang.core.io.ClangIO.*;


/**
 * A single diagnostic, containing the diagnostic's severity,
 * location, text, source ranges, and fix-it hints.
 */
@Namespace @Name("void") @Opaque @Properties(inherit = org.swdc.libclang.conf.LibClangIOConfigure.class)
public class CXDiagnostic extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public CXDiagnostic() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXDiagnostic(Pointer p) { super(p); }
}
