// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class LLamaExt extends org.swdc.llama.config.LLamaExtConfigure {
    static { Loader.load(); }

// Parsed from llama_std_support.h

// #ifndef _H_LLAMA_STD_
// #define _H_LLAMA_STD_

// #include "../include/llama.h"


public static final int LLAMA_POOLING_TYPE_NONE = 0;;
public static final int LLAMA_POOLING_TYPE_MEAN = 1;;
public static final int LLAMA_POOLING_TYPE_CLS =  2;;
public static final int LLAMA_POOLING_TYPE_LAST = 3;;

public static native int ext_llama_pooling_type(llama_context context);

// #endif

}
