// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.pdfium.core.view;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.pdfium.core.PdfiumView.*;

@Opaque @Properties(inherit = org.swdc.pdfium.core.PdfiumViewConfigure.class)
public class fpdf_pathsegment_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public fpdf_pathsegment_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public fpdf_pathsegment_t(Pointer p) { super(p); }
}
