// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.pdfium.core.view;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.pdfium.core.PdfiumView.*;

@Namespace @Name("void") @Opaque @Properties(inherit = org.swdc.pdfium.conf.PdfiumViewConfigure.class)
public class FPDF_SKIA_CANVAS extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public FPDF_SKIA_CANVAS() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FPDF_SKIA_CANVAS(Pointer p) { super(p); }
}
