// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.pdfium.core.view;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.pdfium.core.PdfiumView.*;


@Properties(inherit = org.swdc.pdfium.conf.PdfiumViewConfigure.class)
public class FS_QUADPOINTSF extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public FS_QUADPOINTSF() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public FS_QUADPOINTSF(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FS_QUADPOINTSF(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public FS_QUADPOINTSF position(long position) {
        return (FS_QUADPOINTSF)super.position(position);
    }
    @Override public FS_QUADPOINTSF getPointer(long i) {
        return new FS_QUADPOINTSF((Pointer)this).offsetAddress(i);
    }

  public native @Cast("FS_FLOAT") float x1(); public native FS_QUADPOINTSF x1(float setter);
  public native @Cast("FS_FLOAT") float y1(); public native FS_QUADPOINTSF y1(float setter);
  public native @Cast("FS_FLOAT") float x2(); public native FS_QUADPOINTSF x2(float setter);
  public native @Cast("FS_FLOAT") float y2(); public native FS_QUADPOINTSF y2(float setter);
  public native @Cast("FS_FLOAT") float x3(); public native FS_QUADPOINTSF x3(float setter);
  public native @Cast("FS_FLOAT") float y3(); public native FS_QUADPOINTSF y3(float setter);
  public native @Cast("FS_FLOAT") float x4(); public native FS_QUADPOINTSF x4(float setter);
  public native @Cast("FS_FLOAT") float y4(); public native FS_QUADPOINTSF y4(float setter);
}
