// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.pdfium.core.view;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.pdfium.core.PdfiumView.*;


// Rectangle area(float) in device or page coordinate system.
@Properties(inherit = org.swdc.pdfium.conf.PdfiumViewConfigure.class)
public class FS_RECTF extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public FS_RECTF() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public FS_RECTF(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FS_RECTF(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public FS_RECTF position(long position) {
        return (FS_RECTF)super.position(position);
    }
    @Override public FS_RECTF getPointer(long i) {
        return new FS_RECTF((Pointer)this).offsetAddress(i);
    }

  // The x-coordinate of the left-top corner.
  public native float left(); public native FS_RECTF left(float setter);
  // The y-coordinate of the left-top corner.
  public native float top(); public native FS_RECTF top(float setter);
  // The x-coordinate of the right-bottom corner.
  public native float right(); public native FS_RECTF right(float setter);
  // The y-coordinate of the right-bottom corner.
  public native float bottom(); public native FS_RECTF bottom(float setter);
}
