// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.mariadb.core.com;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.mariadb.core.global.*;
import static org.swdc.mariadb.core.MyGlobal.*;

import static org.swdc.mariadb.core.MyCom.*;


// #ifdef MY_GLOBAL_INCLUDED
// #endif

@Opaque @Properties(inherit = org.swdc.mariadb.conf.MyComConfigure.class)
public class sockaddr extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public sockaddr() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sockaddr(Pointer p) { super(p); }
}
