// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;

// #endif

@Opaque @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_backend_buffer_type extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public ggml_backend_buffer_type() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ggml_backend_buffer_type(Pointer p) { super(p); }
}
