// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;


    // Abort callback
    // If not NULL, called before ggml computation
    // If it returns true, the computation is aborted
    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_abort_callback extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_abort_callback(Pointer p) { super(p); }
        protected ggml_abort_callback() { allocate(); }
        private native void allocate();
        public native @Cast("bool") boolean call(Pointer data);
    }
