// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;

    // Get a list of feature flags supported by the backend (returns a NULL-terminated array)
    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_backend_feature extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_backend_feature() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_backend_feature(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_backend_feature(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_backend_feature position(long position) {
            return (ggml_backend_feature)super.position(position);
        }
        @Override public ggml_backend_feature getPointer(long i) {
            return new ggml_backend_feature((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("const char*") BytePointer name(); public native ggml_backend_feature name(BytePointer setter);
        public native @Cast("const char*") BytePointer value(); public native ggml_backend_feature value(BytePointer setter);
    }
