// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;

// #endif

    // Function type used in fatal error callbacks
    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_abort_callback_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_abort_callback_t(Pointer p) { super(p); }
        protected ggml_abort_callback_t() { allocate(); }
        private native void allocate();
        public native void call(@Cast("const char*") BytePointer error_message);
    }
