// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;

    // Get additional buffer types provided by the device (returns a NULL-terminated array)
    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_backend_dev_get_extra_bufts_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_backend_dev_get_extra_bufts_t(Pointer p) { super(p); }
        protected ggml_backend_dev_get_extra_bufts_t() { allocate(); }
        private native void allocate();
        public native @Cast("ggml_backend_buffer_type**") PointerPointer call(ggml_backend_device device);
    }
