// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;

    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_backend_get_features_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_backend_get_features_t(Pointer p) { super(p); }
        protected ggml_backend_get_features_t() { allocate(); }
        private native void allocate();
        public native ggml_backend_feature call(ggml_backend_reg reg);
    }
