// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;


    // n-dimensional tensor
    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_tensor extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_tensor() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_tensor(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_tensor(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_tensor position(long position) {
            return (ggml_tensor)super.position(position);
        }
        @Override public ggml_tensor getPointer(long i) {
            return new ggml_tensor((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("ggml_type") int type(); public native ggml_tensor type(int setter);

        public native ggml_backend_buffer buffer(); public native ggml_tensor buffer(ggml_backend_buffer setter);

        public native @Cast("int64_t") long ne(int i); public native ggml_tensor ne(int i, long setter);
        @MemberGetter public native @Cast("int64_t*") LongPointer ne(); // number of elements
        public native @Cast("size_t") long nb(int i); public native ggml_tensor nb(int i, long setter);
        @MemberGetter public native @Cast("size_t*") SizeTPointer nb(); // stride in bytes:
                                   // nb[0] = ggml_type_size(type)
                                   // nb[1] = nb[0]   * (ne[0] / ggml_blck_size(type)) + padding
                                   // nb[i] = nb[i-1] * ne[i-1]

        // compute data
        public native @Cast("ggml_op") int op(); public native ggml_tensor op(int setter);

        // op params - allocated as int32_t for alignment
        public native int op_params(int i); public native ggml_tensor op_params(int i, int setter);
        @MemberGetter public native IntPointer op_params();

        public native int flags(); public native ggml_tensor flags(int setter);

        public native ggml_tensor src(int i); public native ggml_tensor src(int i, ggml_tensor setter);
        @MemberGetter public native @Cast("ggml_tensor**") PointerPointer src();

        // source tensor and offset for views
        public native ggml_tensor view_src(); public native ggml_tensor view_src(ggml_tensor setter);
        public native @Cast("size_t") long view_offs(); public native ggml_tensor view_offs(long setter);

        public native Pointer data(); public native ggml_tensor data(Pointer setter);

        public native @Cast("char") byte name(int i); public native ggml_tensor name(int i, byte setter);
        @MemberGetter public native @Cast("char*") BytePointer name();

        public native Pointer extra(); public native ggml_tensor extra(Pointer setter); // extra things e.g. for ggml-cuda.cu

        public native @Cast("char") byte padding(int i); public native ggml_tensor padding(int i, byte setter);
        @MemberGetter public native @Cast("char*") BytePointer padding();
    }
