// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ggml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.llama.core.ggml.GGML.*;


    // TODO these functions were sandwiched in the old optimization interface, is there a better place for them?
    @Properties(inherit = org.swdc.llama.config.GGMLConfigure.class)
public class ggml_log_callback extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_log_callback(Pointer p) { super(p); }
        protected ggml_log_callback() { allocate(); }
        private native void allocate();
        public native void call(@Cast("ggml_log_level") int level, @Cast("const char*") BytePointer text, Pointer user_data);
    }
