// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.mariadb.core.mysql;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.mariadb.core.global.*;
import static org.swdc.mariadb.core.MyGlobal.*;
import org.swdc.mariadb.core.com.*;
import static org.swdc.mariadb.core.MyCom.*;

import static org.swdc.mariadb.core.MariaDB.*;


@Properties(inherit = org.swdc.mariadb.conf.MariaDBConfigure.class)
public class MY_CHARSET_INFO extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public MY_CHARSET_INFO() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MY_CHARSET_INFO(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MY_CHARSET_INFO(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MY_CHARSET_INFO position(long position) {
        return (MY_CHARSET_INFO)super.position(position);
    }
    @Override public MY_CHARSET_INFO getPointer(long i) {
        return new MY_CHARSET_INFO((Pointer)this).offsetAddress(i);
    }

  public native @Cast("unsigned int") int number(); public native MY_CHARSET_INFO number(int setter);     /* character set number              */
  public native @Cast("unsigned int") int state(); public native MY_CHARSET_INFO state(int setter);      /* character set state               */
  public native @Cast("const char*") BytePointer csname(); public native MY_CHARSET_INFO csname(BytePointer setter);    /* collation name                    */
  public native @Cast("const char*") BytePointer name(); public native MY_CHARSET_INFO name(BytePointer setter);      /* character set name                */
  public native @Cast("const char*") BytePointer comment(); public native MY_CHARSET_INFO comment(BytePointer setter);   /* comment                           */
  public native @Cast("const char*") BytePointer dir(); public native MY_CHARSET_INFO dir(BytePointer setter);       /* character set directory           */
  public native @Cast("unsigned int") int mbminlen(); public native MY_CHARSET_INFO mbminlen(int setter);   /* min. length for multibyte strings */
  public native @Cast("unsigned int") int mbmaxlen(); public native MY_CHARSET_INFO mbmaxlen(int setter);   /* max. length for multibyte strings */
}
