// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.mariadb.core.mysql;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.mariadb.core.global.*;
import static org.swdc.mariadb.core.MyGlobal.*;
import org.swdc.mariadb.core.com.*;
import static org.swdc.mariadb.core.MyCom.*;

import static org.swdc.mariadb.core.MariaDB.*;

// #endif


@Properties(inherit = org.swdc.mariadb.conf.MariaDBConfigure.class)
public class MYSQL_PARAMETERS extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public MYSQL_PARAMETERS() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MYSQL_PARAMETERS(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MYSQL_PARAMETERS(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MYSQL_PARAMETERS position(long position) {
        return (MYSQL_PARAMETERS)super.position(position);
    }
    @Override public MYSQL_PARAMETERS getPointer(long i) {
        return new MYSQL_PARAMETERS((Pointer)this).offsetAddress(i);
    }

  public native @Cast("unsigned long*") CLongPointer p_max_allowed_packet(); public native MYSQL_PARAMETERS p_max_allowed_packet(CLongPointer setter);
  public native @Cast("unsigned long*") CLongPointer p_net_buffer_length(); public native MYSQL_PARAMETERS p_net_buffer_length(CLongPointer setter);
  public native Pointer extension(); public native MYSQL_PARAMETERS extension(Pointer setter);
}
