// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for file drop callbacks.
 *
 *  This is the function signature for file drop callbacks.
 *
 *  @param window [in] The window that received the event.
 *  @param count [in] The number of dropped files.
 *  @param paths [in] The UTF-8 encoded file and/or directory path names.
 *
 *  @see \ref path_drop
 *  @see glfwSetDropCallback
 *
 *  @since Added in version 3.1.
 *
 *  \ingroup input
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWdropfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWdropfun(Pointer p) { super(p); }
    protected GLFWdropfun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,int arg1,@Cast("const char**") PointerPointer arg2);
}
