// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for Unicode character callbacks.
 *
 *  This is the function signature for Unicode character callback functions.
 *
 *  @param window [in] The window that received the event.
 *  @param codepoint [in] The Unicode code point of the character.
 *
 *  @see \ref input_char
 *  @see glfwSetCharCallback
 *
 *  @since Added in version 2.4.
 *  \glfw3 Added window handle parameter.
 *
 *  \ingroup input
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWcharfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWcharfun(Pointer p) { super(p); }
    protected GLFWcharfun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,@Cast("unsigned int") int arg1);
}
