// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;

@Opaque @Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWmonitor extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public GLFWmonitor() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GLFWmonitor(Pointer p) { super(p); }
}
