// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for window focus/defocus callbacks.
 *
 *  This is the function signature for window focus callback functions.
 *
 *  @param window [in] The window that gained or lost input focus.
 *  @param focused [in] {@code GLFW_TRUE} if the window was given input focus, or
 *  {@code GLFW_FALSE} if it lost it.
 *
 *  @see \ref window_focus
 *  @see glfwSetWindowFocusCallback
 *
 *  @since Added in version 3.0.
 *
 *  \ingroup window
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWwindowfocusfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWwindowfocusfun(Pointer p) { super(p); }
    protected GLFWwindowfocusfun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,int arg1);
}
