// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for window iconify/restore callbacks.
 *
 *  This is the function signature for window iconify/restore callback
 *  functions.
 *
 *  @param window [in] The window that was iconified or restored.
 *  @param iconified [in] {@code GLFW_TRUE} if the window was iconified, or
 *  {@code GLFW_FALSE} if it was restored.
 *
 *  @see \ref window_iconify
 *  @see glfwSetWindowIconifyCallback
 *
 *  @since Added in version 3.0.
 *
 *  \ingroup window
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWwindowiconifyfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWwindowiconifyfun(Pointer p) { super(p); }
    protected GLFWwindowiconifyfun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,int arg1);
}
