// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for cursor position callbacks.
 *
 *  This is the function signature for cursor position callback functions.
 *
 *  @param window [in] The window that received the event.
 *  @param xpos [in] The new cursor x-coordinate, relative to the left edge of
 *  the client area.
 *  @param ypos [in] The new cursor y-coordinate, relative to the top edge of the
 *  client area.
 *
 *  @see \ref cursor_pos
 *  @see glfwSetCursorPosCallback
 *
 *  @since Added in version 3.0.  Replaces {@code GLFWmouseposfun}.
 *
 *  \ingroup input
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWcursorposfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWcursorposfun(Pointer p) { super(p); }
    protected GLFWcursorposfun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,double arg1,double arg2);
}
