// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for framebuffer resize callbacks.
 *
 *  This is the function signature for framebuffer resize callback
 *  functions.
 *
 *  @param window [in] The window whose framebuffer was resized.
 *  @param width [in] The new width, in pixels, of the framebuffer.
 *  @param height [in] The new height, in pixels, of the framebuffer.
 *
 *  @see \ref window_fbsize
 *  @see glfwSetFramebufferSizeCallback
 *
 *  @since Added in version 3.0.
 *
 *  \ingroup window
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWframebuffersizefun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWframebuffersizefun(Pointer p) { super(p); }
    protected GLFWframebuffersizefun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,int arg1,int arg2);
}
