// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;



/*************************************************************************
 * GLFW API types
 *************************************************************************/

/** \brief Client API function pointer type.
 *
 *  Generic function pointer used for returning client API function pointers
 *  without forcing a cast from a regular pointer.
 *
 *  @see \ref context_glext
 *  @see glfwGetProcAddress
 *
 *  @since Added in version 3.0.
 
 *  \ingroup context
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWglproc extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWglproc(Pointer p) { super(p); }
    protected GLFWglproc() { allocate(); }
    private native void allocate();
    public native void call();
}
