// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for error callbacks.
 *
 *  This is the function signature for error callback functions.
 *
 *  @param error [in] An [error code](\ref errors).
 *  @param description [in] A UTF-8 encoded string describing the error.
 *
 *  @see \ref error_handling
 *  @see glfwSetErrorCallback
 *
 *  @since Added in version 3.0.
 *
 *  \ingroup init
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWerrorfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWerrorfun(Pointer p) { super(p); }
    protected GLFWerrorfun() { allocate(); }
    private native void allocate();
    public native void call(int arg0,@Cast("const char*") BytePointer arg1);
}
