// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief Video mode type.
 *
 *  This describes a single video mode.
 *
 *  @see \ref monitor_modes
 *  @see glfwGetVideoMode glfwGetVideoModes
 *
 *  @since Added in version 1.0.
 *  \glfw3 Added refresh rate member.
 *
 *  \ingroup monitor
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWvidmode extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public GLFWvidmode() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GLFWvidmode(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GLFWvidmode(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public GLFWvidmode position(long position) {
        return (GLFWvidmode)super.position(position);
    }
    @Override public GLFWvidmode getPointer(long i) {
        return new GLFWvidmode((Pointer)this).offsetAddress(i);
    }

    /** The width, in screen coordinates, of the video mode.
     */
    public native int width(); public native GLFWvidmode width(int setter);
    /** The height, in screen coordinates, of the video mode.
     */
    public native int height(); public native GLFWvidmode height(int setter);
    /** The bit depth of the red channel of the video mode.
     */
    public native int redBits(); public native GLFWvidmode redBits(int setter);
    /** The bit depth of the green channel of the video mode.
     */
    public native int greenBits(); public native GLFWvidmode greenBits(int setter);
    /** The bit depth of the blue channel of the video mode.
     */
    public native int blueBits(); public native GLFWvidmode blueBits(int setter);
    /** The refresh rate, in Hz, of the video mode.
     */
    public native int refreshRate(); public native GLFWvidmode refreshRate(int setter);
}
