// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;


/** \brief The function signature for mouse button callbacks.
 *
 *  This is the function signature for mouse button callback functions.
 *
 *  @param window [in] The window that received the event.
 *  @param button [in] The [mouse button](\ref buttons) that was pressed or
 *  released.
 *  @param action [in] One of {@code GLFW_PRESS} or {@code GLFW_RELEASE}.
 *  @param mods [in] Bit field describing which [modifier keys](\ref mods) were
 *  held down.
 *
 *  @see \ref input_mouse_button
 *  @see glfwSetMouseButtonCallback
 *
 *  @since Added in version 1.0.
 *  \glfw3 Added window handle and modifier mask parameters.
 *
 *  \ingroup input
 */
@Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWmousebuttonfun extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLFWmousebuttonfun(Pointer p) { super(p); }
    protected GLFWmousebuttonfun() { allocate(); }
    private native void allocate();
    public native void call(GLFWwindow arg0,int arg1,int arg2,int arg3);
}
