// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.glfw;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUIGLFW.*;
      // IMGUI_IMPL_API
// #ifndef IMGUI_DISABLE

@Opaque @Properties(inherit = org.swdc.imgui.conf.ImGuiGLFWConfigure.class)
public class GLFWwindow extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public GLFWwindow() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GLFWwindow(Pointer p) { super(p); }
}
