// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


/**
 * A single result of code completion.
 */
@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXCompletionResult extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CXCompletionResult() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CXCompletionResult(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXCompletionResult(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CXCompletionResult position(long position) {
        return (CXCompletionResult)super.position(position);
    }
    @Override public CXCompletionResult getPointer(long i) {
        return new CXCompletionResult((Pointer)this).offsetAddress(i);
    }

  /**
   * The kind of entity that this completion refers to.
   *
   * The cursor kind will be a macro, keyword, or a declaration (one of the
   * *Decl cursor kinds), describing the entity that the completion is
   * referring to.
   *
   * \todo In the future, we would like to provide a full cursor, to allow
   * the client to extract additional information from declaration.
   */
  public native @Cast("CXCursorKind") int CursorKind(); public native CXCompletionResult CursorKind(int setter);

  /**
   * The code-completion string that describes how to insert this
   * code-completion result into the editing buffer.
   */
  public native CXCompletionString CompletionString(); public native CXCompletionResult CompletionString(CXCompletionString setter);
}
