// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


// #if __has_feature(blocks)
@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXCursorAndRangeVisitorBlock extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    CXCursorAndRangeVisitorBlock(Pointer p) { super(p); }
    protected CXCursorAndRangeVisitorBlock() { allocate(); }
    private native void allocate();
    public native @Cast("CXVisitorResult") int call(@ByVal CXCursor arg0,
                                                             @ByVal CXSourceRange arg1);
}
