// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


/**
 * Visitor invoked for each field found by a traversal.
 *
 * This visitor function will be invoked for each field found by
 * \c clang_Type_visitFields. Its first argument is the cursor being
 * visited, its second argument is the client data provided to
 * \c clang_Type_visitFields.
 *
 * The visitor should return one of the \c CXVisitorResult values
 * to direct \c clang_Type_visitFields.
 */
@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXFieldVisitor extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    CXFieldVisitor(Pointer p) { super(p); }
    protected CXFieldVisitor() { allocate(); }
    private native void allocate();
    public native @Cast("CXVisitorResult") int call(@ByVal CXCursor C,
                                               CXClientData client_data);
}
