// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXIdxObjCInterfaceDeclInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CXIdxObjCInterfaceDeclInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CXIdxObjCInterfaceDeclInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXIdxObjCInterfaceDeclInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CXIdxObjCInterfaceDeclInfo position(long position) {
        return (CXIdxObjCInterfaceDeclInfo)super.position(position);
    }
    @Override public CXIdxObjCInterfaceDeclInfo getPointer(long i) {
        return new CXIdxObjCInterfaceDeclInfo((Pointer)this).offsetAddress(i);
    }

  public native @Const CXIdxObjCContainerDeclInfo containerInfo(); public native CXIdxObjCInterfaceDeclInfo containerInfo(CXIdxObjCContainerDeclInfo setter);
  public native @Const CXIdxBaseClassInfo superInfo(); public native CXIdxObjCInterfaceDeclInfo superInfo(CXIdxBaseClassInfo setter);
  public native @Const CXIdxObjCProtocolRefListInfo protocols(); public native CXIdxObjCInterfaceDeclInfo protocols(CXIdxObjCProtocolRefListInfo setter);
}
