// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXIdxObjCProtocolRefInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CXIdxObjCProtocolRefInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CXIdxObjCProtocolRefInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXIdxObjCProtocolRefInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CXIdxObjCProtocolRefInfo position(long position) {
        return (CXIdxObjCProtocolRefInfo)super.position(position);
    }
    @Override public CXIdxObjCProtocolRefInfo getPointer(long i) {
        return new CXIdxObjCProtocolRefInfo((Pointer)this).offsetAddress(i);
    }

  public native @Const CXIdxEntityInfo protocol(); public native CXIdxObjCProtocolRefInfo protocol(CXIdxEntityInfo setter);
  public native @ByRef CXCursor cursor(); public native CXIdxObjCProtocolRefInfo cursor(CXCursor setter);
  public native @ByRef CXIdxLoc loc(); public native CXIdxObjCProtocolRefInfo loc(CXIdxLoc setter);
}
