// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


/**
 * An indexing action/session, to be applied to one or multiple
 * translation units.
 */
@Namespace @Name("void") @Opaque @Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXIndexAction extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public CXIndexAction() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXIndexAction(Pointer p) { super(p); }
}
