// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


/**
 * Opaque pointer representing a policy that controls pretty printing
 * for \c clang_getCursorPrettyPrinted.
 */
@Namespace @Name("void") @Opaque @Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXPrintingPolicy extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public CXPrintingPolicy() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXPrintingPolicy(Pointer p) { super(p); }
}
