// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


/**
 * An opaque type representing target information for a given translation
 * unit.
 */
@Opaque @Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXTargetInfoImpl extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public CXTargetInfoImpl() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXTargetInfoImpl(Pointer p) { super(p); }
}
