// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;


/**
 * The type of an element in the abstract syntax tree.
 *
 */
@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class CXType extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CXType() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CXType(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CXType(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CXType position(long position) {
        return (CXType)super.position(position);
    }
    @Override public CXType getPointer(long i) {
        return new CXType((Pointer)this).offsetAddress(i);
    }

  public native @Cast("CXTypeKind") int kind(); public native CXType kind(int setter);
  public native Pointer data(int i); public native CXType data(int i, Pointer setter);
  @MemberGetter public native @Cast("void**") PointerPointer data();
}
