// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.libclang.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.libclang.core.io.*;
import static org.swdc.libclang.core.io.ClangIO.*;

import static org.swdc.libclang.core.LibClang.*;

@Properties(inherit = org.swdc.libclang.conf.LibClangConfigure.class)
public class Fn_Pointer extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    Fn_Pointer(Pointer p) { super(p); }
    protected Fn_Pointer() { allocate(); }
    private native void allocate();
    public native void call(Pointer arg0);
}
