// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.llama.core.ext;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.swdc.llama.core.ggml.*;
import static org.swdc.llama.core.ggml.GGML.*;
import org.swdc.llama.core.*;
import static org.swdc.llama.core.LLamaCore.*;

import static org.swdc.llama.core.LLamaExt.*;

@Name("std::vector<char>") @Properties(inherit = org.swdc.llama.config.LLamaExtConfigure.class)
public class CharVec extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CharVec(Pointer p) { super(p); }
    public CharVec(byte value) { this(1); put(0, value); }
    public CharVec(byte ... array) { this(array.length); put(array); }
    public CharVec()       { allocate();  }
    public CharVec(long n) { allocate(n); }
    private native void allocate();
    private native void allocate(@Cast("size_t") long n);
    public native @Name("operator =") @ByRef CharVec put(@ByRef CharVec x);

    public boolean empty() { return size() == 0; }
    public native long size();
    public void clear() { resize(0); }
    public native void resize(@Cast("size_t") long n);

    public byte front() { return get(0); }
    public byte back() { return get(size() - 1); }
    @Index(function = "at") public native @Cast("char") byte get(@Cast("size_t") long i);
    public native CharVec put(@Cast("size_t") long i, byte value);

    public native @ByVal Iterator insert(@ByVal Iterator pos, @Cast("char") byte value);
    public native @ByVal Iterator erase(@ByVal Iterator pos);
    public native @ByVal Iterator begin();
    public native @ByVal Iterator end();
    @NoOffset @Name("iterator") public static class Iterator extends Pointer {
        public Iterator(Pointer p) { super(p); }
        public Iterator() { }

        public native @Name("operator ++") @ByRef Iterator increment();
        public native @Name("operator ==") boolean equals(@ByRef Iterator it);
        public native @Name("operator *") @Cast("char") byte get();
    }

    public byte[] get() {
        byte[] array = new byte[size() < Integer.MAX_VALUE ? (int)size() : Integer.MAX_VALUE];
        for (int i = 0; i < array.length; i++) {
            array[i] = get(i);
        }
        return array;
    }
    @Override public String toString() {
        return java.util.Arrays.toString(get());
    }

    public byte pop_back() {
        long size = size();
        byte value = get(size - 1);
        resize(size - 1);
        return value;
    }
    public CharVec push_back(byte value) {
        long size = size();
        resize(size + 1);
        return put(size, value);
    }
    public CharVec put(byte value) {
        if (size() != 1) { resize(1); }
        return put(0, value);
    }
    public CharVec put(byte ... array) {
        if (size() != array.length) { resize(array.length); }
        for (int i = 0; i < array.length; i++) {
            put(i, array[i]);
        }
        return this;
    }
}

