// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;
           // Separate items with \0 within a string, end item-list with \0\0. e.g. "One\0Two\0Three\0"
@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class Getter_Pointer_int extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    Getter_Pointer_int(Pointer p) { super(p); }
    protected Getter_Pointer_int() { allocate(); }
    private native void allocate();
    public native @Cast("const char*") BytePointer call(Pointer user_data, int idx);
}
