// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Vertex layout
// #ifndef IMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT
@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImDrawVert extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImDrawVert() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImDrawVert(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImDrawVert(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImDrawVert position(long position) {
        return (ImDrawVert)super.position(position);
    }
    @Override public ImDrawVert getPointer(long i) {
        return new ImDrawVert((Pointer)this).offsetAddress(i);
    }

    public native @ByRef ImVec2 pos(); public native ImDrawVert pos(ImVec2 setter);
    public native @ByRef ImVec2 uv(); public native ImDrawVert uv(ImVec2 setter);
    public native @Cast("ImU32") int col(); public native ImDrawVert col(int setter);
}
