// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;
                     // Output new ranges (ImVector_Construct()/ImVector_Destruct() can be used to safely construct out_ranges)

// See ImFontAtlas::AddCustomRectXXX functions.
@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImFontAtlasCustomRect extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImFontAtlasCustomRect() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImFontAtlasCustomRect(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImFontAtlasCustomRect(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImFontAtlasCustomRect position(long position) {
        return (ImFontAtlasCustomRect)super.position(position);
    }
    @Override public ImFontAtlasCustomRect getPointer(long i) {
        return new ImFontAtlasCustomRect((Pointer)this).offsetAddress(i);
    }

    public native @Cast("unsigned short") short Width(); public native ImFontAtlasCustomRect Width(short setter);
    public native @Cast("unsigned short") short Height(); public native ImFontAtlasCustomRect Height(short setter);  // Input    // Desired rectangle dimension
    public native @Cast("unsigned short") short X(); public native ImFontAtlasCustomRect X(short setter);
    public native @Cast("unsigned short") short Y(); public native ImFontAtlasCustomRect Y(short setter);           // Output   // Packed position in Atlas
    public native @Cast("unsigned int") int GlyphID(); public native ImFontAtlasCustomRect GlyphID(int setter);        // Input    // For custom font glyphs only (ID < 0x110000)
    public native float GlyphAdvanceX(); public native ImFontAtlasCustomRect GlyphAdvanceX(float setter);  // Input    // For custom font glyphs only: glyph xadvance
    public native @ByRef ImVec2 GlyphOffset(); public native ImFontAtlasCustomRect GlyphOffset(ImVec2 setter);    // Input    // For custom font glyphs only: glyph display offset
    public native ImFont Font(); public native ImFontAtlasCustomRect Font(ImFont setter);           // Input    // For custom font glyphs only: target font
}
