// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


//-----------------------------------------------------------------------------
// [SECTION] Platform Dependent Interfaces
//-----------------------------------------------------------------------------

// (Optional) Support for IME (Input Method Editor) via the io.PlatformSetImeDataFn() function.
@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImGuiPlatformImeData extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImGuiPlatformImeData() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImGuiPlatformImeData(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImGuiPlatformImeData(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImGuiPlatformImeData position(long position) {
        return (ImGuiPlatformImeData)super.position(position);
    }
    @Override public ImGuiPlatformImeData getPointer(long i) {
        return new ImGuiPlatformImeData((Pointer)this).offsetAddress(i);
    }

    public native @Cast("bool") boolean WantVisible(); public native ImGuiPlatformImeData WantVisible(boolean setter);      // A widget wants the IME to be visible
    public native @ByRef ImVec2 InputPos(); public native ImGuiPlatformImeData InputPos(ImVec2 setter);         // Position of the input cursor
    public native float InputLineHeight(); public native ImGuiPlatformImeData InputLineHeight(float setter);  // Line height
}
