// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImFontAtlasCustomRect>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImFontAtlasCustomRect extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImFontAtlasCustomRect() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImFontAtlasCustomRect(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImFontAtlasCustomRect(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImFontAtlasCustomRect position(long position) {
        return (ImVector_ImFontAtlasCustomRect)super.position(position);
    }
    @Override public ImVector_ImFontAtlasCustomRect getPointer(long i) {
        return new ImVector_ImFontAtlasCustomRect((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImFontAtlasCustomRect Size(int setter);
    public native int Capacity(); public native ImVector_ImFontAtlasCustomRect Capacity(int setter);
    public native ImFontAtlasCustomRect Data(); public native ImVector_ImFontAtlasCustomRect Data(ImFontAtlasCustomRect setter);
}
