// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImDrawChannel>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImDrawChannel extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImDrawChannel() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImDrawChannel(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImDrawChannel(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImDrawChannel position(long position) {
        return (ImVector_ImDrawChannel)super.position(position);
    }
    @Override public ImVector_ImDrawChannel getPointer(long i) {
        return new ImVector_ImDrawChannel((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImDrawChannel Size(int setter);
    public native int Capacity(); public native ImVector_ImDrawChannel Capacity(int setter);
    public native ImDrawChannel Data(); public native ImVector_ImDrawChannel Data(ImDrawChannel setter);
}
