// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImVec4>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImVec4 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImVec4() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImVec4(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImVec4(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImVec4 position(long position) {
        return (ImVector_ImVec4)super.position(position);
    }
    @Override public ImVector_ImVec4 getPointer(long i) {
        return new ImVector_ImVec4((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImVec4 Size(int setter);
    public native int Capacity(); public native ImVector_ImVec4 Capacity(int setter);
    public native ImVec4 Data(); public native ImVector_ImVec4 Data(ImVec4 setter);
}
