// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<char>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_char extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_char() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_char(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_char(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_char position(long position) {
        return (ImVector_char)super.position(position);
    }
    @Override public ImVector_char getPointer(long i) {
        return new ImVector_char((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_char Size(int setter);
    public native int Capacity(); public native ImVector_char Capacity(int setter);
    public native @Cast("char*") BytePointer Data(); public native ImVector_char Data(BytePointer setter);
}
