// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImGuiViewport*>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImGuiViewportPtr extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImGuiViewportPtr() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImGuiViewportPtr(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImGuiViewportPtr(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImGuiViewportPtr position(long position) {
        return (ImVector_ImGuiViewportPtr)super.position(position);
    }
    @Override public ImVector_ImGuiViewportPtr getPointer(long i) {
        return new ImVector_ImGuiViewportPtr((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImGuiViewportPtr Size(int setter);
    public native int Capacity(); public native ImVector_ImGuiViewportPtr Capacity(int setter);
    public native ImGuiViewport Data(int i); public native ImVector_ImGuiViewportPtr Data(int i, ImGuiViewport setter);
    public native @Cast("ImGuiViewport**") PointerPointer Data(); public native ImVector_ImGuiViewportPtr Data(PointerPointer setter);
}
