// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImDrawVert>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImDrawVert extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImDrawVert() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImDrawVert(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImDrawVert(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImDrawVert position(long position) {
        return (ImVector_ImDrawVert)super.position(position);
    }
    @Override public ImVector_ImDrawVert getPointer(long i) {
        return new ImVector_ImDrawVert((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImDrawVert Size(int setter);
    public native int Capacity(); public native ImVector_ImDrawVert Capacity(int setter);
    public native ImDrawVert Data(); public native ImVector_ImDrawVert Data(ImDrawVert setter);
}
