// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImGuiSelectionRequest>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImGuiSelectionRequest extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImGuiSelectionRequest() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImGuiSelectionRequest(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImGuiSelectionRequest(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImGuiSelectionRequest position(long position) {
        return (ImVector_ImGuiSelectionRequest)super.position(position);
    }
    @Override public ImVector_ImGuiSelectionRequest getPointer(long i) {
        return new ImVector_ImGuiSelectionRequest((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImGuiSelectionRequest Size(int setter);
    public native int Capacity(); public native ImVector_ImGuiSelectionRequest Capacity(int setter);
    public native ImGuiSelectionRequest Data(); public native ImVector_ImGuiSelectionRequest Data(ImGuiSelectionRequest setter);
}
