// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImDrawIdx>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImDrawIdx extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImDrawIdx() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImDrawIdx(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImDrawIdx(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImDrawIdx position(long position) {
        return (ImVector_ImDrawIdx)super.position(position);
    }
    @Override public ImVector_ImDrawIdx getPointer(long i) {
        return new ImVector_ImDrawIdx((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImDrawIdx Size(int setter);
    public native int Capacity(); public native ImVector_ImDrawIdx Capacity(int setter);
    public native @Cast("ImDrawIdx*") ShortPointer Data(); public native ImVector_ImDrawIdx Data(ShortPointer setter);
}
