// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<float>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_float extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_float() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_float(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_float(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_float position(long position) {
        return (ImVector_float)super.position(position);
    }
    @Override public ImVector_float getPointer(long i) {
        return new ImVector_float((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_float Size(int setter);
    public native int Capacity(); public native ImVector_float Capacity(int setter);
    public native FloatPointer Data(); public native ImVector_float Data(FloatPointer setter);
}
