// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImTextureID>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImTextureID extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImTextureID() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImTextureID(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImTextureID(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImTextureID position(long position) {
        return (ImVector_ImTextureID)super.position(position);
    }
    @Override public ImVector_ImTextureID getPointer(long i) {
        return new ImVector_ImTextureID((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImTextureID Size(int setter);
    public native int Capacity(); public native ImVector_ImTextureID Capacity(int setter);
    public native @ByPtrPtr ImTextureID Data(); public native ImVector_ImTextureID Data(ImTextureID setter);
}
