// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImFontGlyph>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImFontGlyph extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImFontGlyph() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImFontGlyph(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImFontGlyph(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImFontGlyph position(long position) {
        return (ImVector_ImFontGlyph)super.position(position);
    }
    @Override public ImVector_ImFontGlyph getPointer(long i) {
        return new ImVector_ImFontGlyph((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImFontGlyph Size(int setter);
    public native int Capacity(); public native ImVector_ImFontGlyph Capacity(int setter);
    public native ImFontGlyph Data(); public native ImVector_ImFontGlyph Data(ImFontGlyph setter);
}
