// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// ImVec4: 4D vector used to store clipping rectangles, colors etc. [Compile-time configurable type]
@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVec4 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVec4() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVec4(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVec4(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVec4 position(long position) {
        return (ImVec4)super.position(position);
    }
    @Override public ImVec4 getPointer(long i) {
        return new ImVec4((Pointer)this).offsetAddress(i);
    }

    public native float x(); public native ImVec4 x(float setter);
    public native float y(); public native ImVec4 y(float setter);
    public native float z(); public native ImVec4 z(float setter);
    public native float w(); public native ImVec4 w(float setter);
}
