// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;


// Instantiation of ImVector<ImGuiPlatformMonitor>

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class ImVector_ImGuiPlatformMonitor extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public ImVector_ImGuiPlatformMonitor() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ImVector_ImGuiPlatformMonitor(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ImVector_ImGuiPlatformMonitor(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public ImVector_ImGuiPlatformMonitor position(long position) {
        return (ImVector_ImGuiPlatformMonitor)super.position(position);
    }
    @Override public ImVector_ImGuiPlatformMonitor getPointer(long i) {
        return new ImVector_ImGuiPlatformMonitor((Pointer)this).offsetAddress(i);
    }

    public native int Size(); public native ImVector_ImGuiPlatformMonitor Size(int setter);
    public native int Capacity(); public native ImVector_ImGuiPlatformMonitor Capacity(int setter);
    public native ImGuiPlatformMonitor Data(); public native ImVector_ImGuiPlatformMonitor Data(ImGuiPlatformMonitor setter);
}
