// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.swdc.imgui.core.imgui;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.swdc.imgui.core.ImGUICore.*;

@Properties(inherit = org.swdc.imgui.conf.ImGuiCoreConfigure.class)
public class Values_getter_Pointer_int extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    Values_getter_Pointer_int(Pointer p) { super(p); }
    protected Values_getter_Pointer_int() { allocate(); }
    private native void allocate();
    public native float call(Pointer data, int idx);
}
